name: Build macOS App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller --windowed --onefile "Webcrawler GUI v2.0.8 med video.py"
      - uses: actions/upload-artifact@v4
        with:
          name: MacOS-App
          path: dist/
